### ISSUE TITLE
Nothing breakable in this organization

### ISSUE THREAD

**Issue by paulmasson** [webMath/cookbook#1]
@theo-armour r1 of chart-nurbs uses r87 of Three.js while the other versions use dev. Do you need something specific in dev for this document? Otherwise switch all versions to r87.

Rule number one of webMath: nothing breakable in this organization. No Three.js dev.

**Comment by paulmasson** [comment]
chart-nurbs fixed as part of df0d34f8e48da009aa3d539b8837f8f04f6502f3

**Comment by theo-armour** [comment]
@paulmasson 

Interesting. I fixed them too - late last night.

**Comment by paulmasson** [comment]
@theo-armour hence the reference to your commit...

**Comment by theo-armour** [comment]
oops I thought it was yours. ;-)
